---
collections:
  - name: ansible.posix
    version: ">=1.5.0"
  - name: community.general
    version: ">=6.0.0"
  - name: ansible.utils
    version: ">=2.9.0"
  # Optional: for Splunk integration
  # - name: splunk.es
  #   version: ">=2.1.0"