---
# Main tasks for ids_base role
- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - default.yml
  tags: [always]

- name: Perform pre-installation checks
  ansible.builtin.include_tasks: preflight.yml
  tags: [preflight, install]

- name: Install system dependencies
  ansible.builtin.include_tasks: dependencies.yml
  tags: [dependencies, install]

- name: Create IDS directory structure
  ansible.builtin.include_tasks: directories.yml
  tags: [directories, install]

- name: Set up IDS user and permissions
  ansible.builtin.include_tasks: users.yml
  when: ids_dedicated_user | default(false)
  tags: [users, install]

- name: Configure system limits and kernel parameters
  ansible.builtin.include_tasks: system.yml
  tags: [system, install]

- name: Set up log rotation
  ansible.builtin.include_tasks: logrotate.yml
  tags: [logrotate, install]