---
# Main tasks for ids_config role
- name: Deploy IDS configuration
  ansible.builtin.template:
    src: ids.conf.j2
    dest: "{{ ids_config_path }}/ids.conf"
    owner: "{{ ids_user }}"
    group: "{{ ids_group }}"
    mode: "0640"
    backup: yes
  notify: restart ids
  tags: [config]

- name: Deploy environment-specific configurations
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ ids_config_path }}/{{ item }}"
    owner: "{{ ids_user }}"
    group: "{{ ids_group }}"
    mode: "0640"
  loop:
    - thresholds.conf
    - alerts.conf
    - checks.conf
  notify: restart ids
  tags: [config]

- name: Deploy custom check scripts
  ansible.builtin.template:
    src: checks/{{ item }}.j2
    dest: "{{ ids_base_path }}/bin/checks/{{ item }}"
    owner: "{{ ids_user }}"
    group: "{{ ids_group }}"
    mode: "0755"
  loop:
    - check_system.sh
    - check_network.sh
    - check_users.sh
    - check_files.sh
  tags: [config, checks]

- name: Validate configuration
  ansible.builtin.command: "{{ ids_base_path }}/bin/setup.sh --validate-config"
  register: config_validation
  changed_when: false
  failed_when: config_validation.rc != 0
  tags: [config, validate]