---
all:
  children:
    ids_servers:
      children:
        ubuntu_servers:
          hosts:
            ubuntu-web01:
              ansible_host: 10.0.1.10
              ids_role: frontend
            ubuntu-web02:
              ansible_host: 10.0.1.11
              ids_role: frontend
          vars:
            ansible_python_interpreter: /usr/bin/python3

        rhel_servers:
          hosts:
            rhel-app01:
              ansible_host: 10.0.2.20
              ids_role: backend
            rhel-app02:
              ansible_host: 10.0.2.21
              ids_role: backend
          vars:
            ansible_python_interpreter: /usr/bin/python3

        alpine_servers:
          hosts:
            alpine-edge01:
              ansible_host: 10.0.3.30
              ids_role: edge
          vars:
            ansible_python_interpreter: /usr/bin/python3

    monitoring:
      hosts:
        monitor01:
          ansible_host: 10.0.0.100

    splunk_forwarders:
      children:
        ids_servers:
      vars:
        splunk_enabled: true
        splunk_server: splunk.internal.com
        splunk_port: 9997

  vars:
    # Global variables
    ids_base_path: /opt/ids
    ids_log_path: /var/log/ids
    ids_config_path: /etc/ids
    ids_user: root
    ids_group: root

    # Service configuration
    ids_service_type: systemd  # systemd, initd, or cron
    ids_service_enabled: true
    ids_service_state: started

    # Alert configuration
    ids_alert_enabled: true
    ids_alert_webhook: "{{ vault_alert_webhook }}"
    ids_alert_email: security@example.com

    # Monitoring configuration
    ids_check_interval: 300  # seconds
    ids_baseline_interval: 86400  # daily
    ids_log_retention_days: 30