---
# Main tasks for ids_monitor role
- name: Deploy monitoring scripts
  ansible.builtin.include_tasks: deploy_scripts.yml
  tags: [monitor, deploy]

- name: Configure service management
  ansible.builtin.include_tasks: "service_{{ ids_service_type }}.yml"
  tags: [monitor, service]

- name: Validate monitoring setup
  ansible.builtin.include_tasks: validate.yml
  tags: [monitor, validate]

- name: Start monitoring service
  ansible.builtin.include_tasks: start_service.yml
  when: ids_service_state == "started"
  tags: [monitor, service]