---
all:
  children:
    ids_servers:
      hosts:
        staging-01:
          ansible_host: 192.168.100.10
          ids_role: test
        staging-02:
          ansible_host: 192.168.100.11
          ids_role: test
      vars:
        ansible_python_interpreter: /usr/bin/python3

  vars:
    # Override production defaults for staging
    ids_base_path: /opt/ids
    ids_log_path: /var/log/ids
    ids_config_path: /etc/ids
    ids_user: root
    ids_group: root

    # Staging-specific settings
    ids_service_type: systemd
    ids_service_enabled: true
    ids_service_state: started

    # Staging alerts (less aggressive)
    ids_alert_enabled: true
    ids_alert_webhook: "{{ vault_staging_webhook }}"
    ids_alert_email: devops@example.com

    # More frequent checks in staging
    ids_check_interval: 60
    ids_baseline_interval: 3600
    ids_log_retention_days: 7

    # Debugging
    ids_debug_enabled: true
    ids_verbose_logging: true